In [2]:
%pip install fastapi python-dotenv uvicorn nest_asyncio
%pip install Jinja2
%pip install tensorflow
%pip install python-multipart


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install flask


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import uvicorn
import nest_asyncio
from threading import Thread

# 允許 Jupyter 重複使用事件 loop
nest_asyncio.apply()

def run_app():
    # 移除 reload=True，避免 signal 問題
    uvicorn.run("main:app", host="127.0.0.1", port=8000)
    # uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)

# 使用 Thread 非同步啟動 FastAPI
server_thread = Thread(target=run_app, daemon=True)
server_thread.start()

2025-11-06 03:32:48.887921: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-06 03:32:48.895074: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1762399968.903531 1232624 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1762399968.906131 1232624 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1762399968.912847 1232624 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

SSH_HOST: 140.127.22.195
MONGO_HOST: localhost
ALLOWED_ORIGINS: http://localhost,http://127.0.0.1,http://127.0.0.1:8000


INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)


🔗 MongoDB 連線已建立
INFO:     127.0.0.1:41014 - "GET / HTTP/1.1" 302 Found
INFO:     127.0.0.1:41014 - "GET /AnimalManager HTTP/1.1" 200 OK
INFO:     127.0.0.1:41014 - "GET /static/js/auth.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41026 - "GET /static/js/ForgotPW.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41042 - "GET /static/img/background.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:41014 - "GET /static/js/loadCollection.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41026 - "GET /static/js/localStorage.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41042 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:41042 - "GET /AnimalManager/gene HTTP/1.1" 200 OK
INFO:     127.0.0.1:41026 - "GET /static/js/loadGene.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41014 - "GET /static/img/addGene.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:41042 - "GET /static/css/format.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41026 - "GET /gene/collections HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:41026 - "GET /AnimalManager/gen

In [5]:
import tensorflow as tf
print(tf.config.list_physical_devices("GPU"))


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [6]:
import tensorflow as tf
print(tf.sysconfig.get_build_info()["cuda_version"])
print(tf.sysconfig.get_build_info()["cudnn_version"])


12.5.1
9


In [7]:
import tensorflow as tf
with tf.device("/GPU:0"):
    a = tf.random.uniform((1000, 1000))
    b = tf.random.uniform((1000, 1000))
    c = tf.matmul(a, b)
print(c)


I0000 00:00:1762398671.076348 1229591 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14273 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4080 SUPER, pci bus id: 0000:01:00.0, compute capability: 8.9


tf.Tensor(
[[263.8593  254.38826 247.81313 ... 245.53867 256.93304 257.7481 ]
 [257.57248 248.74632 237.6261  ... 236.72572 241.54376 247.61823]
 [261.82022 249.0294  246.31833 ... 239.93279 251.74222 250.00221]
 ...
 [269.4304  260.59106 247.75117 ... 245.6918  248.28087 256.43008]
 [257.3279  252.9885  248.52728 ... 239.49141 245.62587 247.8893 ]
 [255.71815 245.51183 233.55171 ... 231.98024 242.77438 243.78284]], shape=(1000, 1000), dtype=float32)


In [8]:
import tensorflow as tf
print(tf.__version__)
print("GPU Available:", tf.config.list_physical_devices("GPU"))


2.19.0
GPU Available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [9]:
import tensorflow as tf

# 建立一個大矩陣乘法來測試 GPU
with tf.device("/GPU:0"):
    a = tf.random.normal([5000, 5000])
    b = tf.random.normal([5000, 5000])
    c = tf.matmul(a, b)

print("c shape:", c.shape)


c shape: (5000, 5000)
